/* do not change this file, it is auto generated by storybook. */
/// <reference types="@storybook/react-native/metro-env" />
import {
	start,
	updateView,
	View,
	type Features,
} from '@storybook/react-native';

import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-controls/register';

const normalizedStories = [
	{
		titlePrefix: '',
		directory: './src/components/ui',
		files: '**/*.stories.?(ts|tsx)',
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		req: require.context(
			'../src/components/ui',
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		),
	},
	{
		titlePrefix: '',
		directory: './src/components/media',
		files: '**/*.stories.?(ts|tsx)',
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		req: require.context(
			'../src/components/media',
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		),
	},
	{
		titlePrefix: '',
		directory: './src/features/properties/components',
		files: '**/*.stories.?(ts|tsx)',
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		req: require.context(
			'../src/features/properties/components',
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx)?)$/,
		),
	},
];

declare global {
	var view: View;
	var STORIES: typeof normalizedStories;
	var STORYBOOK_WEBSOCKET:
		| { host?: string; port?: number; secured?: boolean }
		| undefined;
	var FEATURES: Features;
}

const annotations = [
	require('./preview'),
	require('@storybook/react-native/preview'),
];

globalThis.STORIES = normalizedStories;

module?.hot?.accept?.();

if (!globalThis.view) {
	globalThis.view = start({
		annotations,
		storyEntries: normalizedStories,
	});
} else {
	updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
